version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: taksu_postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taksu
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
